on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    - name: Install Dependencies
      run: sudo apt-get install libarchive-zip-perl
    - name: Build
      run: |
        git clone https://github.com/particle-iot/device-os.git
        cd device-os
        git checkout release/stable
        cd main
        cp -r ../../Particle/lib/OneWireLibrary/src/* ../../Particle/src
        cp -r ../../Particle/lib/SdFat/src/* ../../Particle/src
        make all PLATFORM=electron APPDIR=../../Particle/src
