
on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Particle
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
          npm install -g particle-cli
    - name: Run Particle
      run: |
        cd Particle
        particle compile electron .
